# Generated by Django 4.0.4 on 2022-04-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='viewers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
