# Generated by Django 4.0.4 on 2022-04-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder_app', '0002_alter_reminder_tags_alter_reminder_viewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='due_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
