# Generated by Django 4.0.4 on 2022-04-11 17:38

from django.db import migrations, models
import reminder_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder_app', '0003_alter_reminder_description_alter_reminder_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='editors',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='viewers',
        ),
        migrations.AddField(
            model_name='reminder',
            name='access_rights',
            field=models.JSONField(default=reminder_app.models.generate_accesses),
        ),
    ]
